{% set name = "split-file-reader" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/split_file_reader-{{ version }}.tar.gz
  sha256: 45bf503999640dd8c38a200878a5f4e9d6486ac57b26c953c13b5eea4da8852a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - split_file_reader = split_file_reader.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7

test:
  imports:
    - split_file_reader
  commands:
    - split_file_reader --help

about:
  home: https://pypi.org/project/split-file-reader/
  summary: 'A package to read parted files on disk.'
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  description: |
    A collection of tools designed to produce and consume data across multiple files as though they were single,
    cohesive files. The modules are fully file-like, and completely transparent to anything that a Python object
    might require when manipulating files.

extra:
  recipe-maintainers:
    - mencian
